# Generated by Django 2.2.3 on 2019-07-18 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_composicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='definicao',
            options={'ordering': ('user__username', 'name'), 'verbose_name': 'Definições', 'verbose_name_plural': 'Definição'},
        ),
        migrations.AlterField(
            model_name='composicao',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Acao', verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='composicao',
            name='definicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteira.Definicao', verbose_name='Definição'),
        ),
        migrations.AlterField(
            model_name='definicao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
