# Generated by Django 2.2.3 on 2019-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'ordering': ('code', 'name'),
                'verbose_name': 'ação',
                'verbose_name_plural': 'ações',
            },
        ),
    ]
